const personnel = [
    {
        id: 1,
        fullName: 'Іванов Іван Іванович',
        passportData: 'XX123456',
        education: 'Вища',
        specialty: 'Інженер-програміст',
        department: 'IT',
        position: 'Senior Developer',
        salary: 5000,
        age: 35,
        healthStatus: 'Здоровий',
        dateOfHiring: '2022-01-15',
        lastAppointment: '2023-05-20'
    },
    {
        id: 2,
        fullName: 'Петров Петро Петрович',
        passportData: 'YY789012',
        education: 'Середня',
        specialty: 'Бухгалтер',
        department: 'Фінанси',
        position: 'Головний бухгалтер',
        salary: 4500,
        age: 40,
        healthStatus: 'Здоровий',
        dateOfHiring: '2021-03-10',
        lastAppointment: '2023-02-18'
    },
    {
        id: 3,
        fullName: 'Сидоров Сидір Сидорович',
        passportData: 'ZZ654321',
        education: 'Вища',
        specialty: 'Менеджер з продажу',
        department: 'Продажі',
        position: 'Керівник відділу продажів',
        salary: 4800,
        age: 63,
        healthStatus: 'Здоровий',
        dateOfHiring: '2020-11-05',
        lastAppointment: '2023-03-25'
    },
    {
        id: 4,
        fullName: 'Коваленко Олександр Олександрович',
        passportData: 'AA111111',
        education: 'Вища',
        specialty: 'HR-менеджер',
        department: 'HR',
        position: 'HR Director',
        salary: 5500,
        age: 45,
        healthStatus: 'Здоровий',
        dateOfHiring: '2019-06-20',
        lastAppointment: '2023-01-10'
    },
    {
        id: 5,
        fullName: 'Михайленко Ірина Олександрівна',
        passportData: 'BB222222',
        education: 'Вища',
        specialty: 'Маркетолог',
        department: 'Маркетинг',
        position: 'Головний маркетолог',
        salary: 4700,
        age: 55,
        healthStatus: 'Здорова',
        dateOfHiring: '2020-02-15',
        lastAppointment: '2023-04-30'
    },
    {
        id: 6,
        fullName: 'Лисенко Володимир Володимирович',
        passportData: 'CC333333',
        education: 'Середня',
        specialty: 'Офіс-менеджер',
        department: 'Адміністрація',
        position: 'Офіс-менеджер',
        salary: 3800,
        age: 63,
        healthStatus: 'Здоровий',
        dateOfHiring: '2021-09-10',
        lastAppointment: '2023-06-05'
    },
    {
        id: 7,
        fullName: 'Кузьмін Віктор Олександрович',
        passportData: 'DD444444',
        education: 'Середня',
        specialty: 'Електрик',
        department: 'Технічне обслуговування',
        position: 'Головний електрик',
        salary: 4200,
        age: 42,
        healthStatus: 'Здоровий',
        dateOfHiring: '2018-12-08',
        lastAppointment: '2023-03-15'
    },
    {
        id: 8,
        fullName: 'Бойко Наталія Петрівна',
        passportData: 'EE555555',
        education: 'Вища',
        specialty: 'Юрист',
        department: 'Юридичний відділ',
        position: 'Керівник юридичного відділу',
        salary: 5300,
        age: 53,
        healthStatus: 'Здорова',
        dateOfHiring: '2017-07-25',
        lastAppointment: '2023-02-20'
    },
    {
        id: 9,
        fullName: 'Даниленко Олег Васильович',
        passportData: 'FF666666',
        education: 'Вища',
        specialty: 'Лікар',
        department: 'Медичний відділ',
        position: 'Лікар загальної практики',
        salary: 5100,
        age: 59,
        healthStatus: 'Здоровий',
        dateOfHiring: '2019-04-12',
        lastAppointment: '2023-05-28'
    },
    {
        id: 10,
        fullName: 'Марченко Оксана Миколаївна',
        passportData: 'GG777777',
        education: 'Вища',
        specialty: 'Дизайнер',
        department: 'Дизайн',
        position: 'Головний дизайнер',
        salary: 4600,
        age: 78,
        healthStatus: 'Здорова',
        dateOfHiring: '2020-08-20',
        lastAppointment: '2023-06-10'
    },
    {
        id: 11,
        fullName: 'Семененко Віталій Ігорович',
        passportData: 'HH888888',
        education: 'Вища',
        specialty: 'Аналітик',
        department: 'Аналітика',
        position: 'Аналітик даних',
        salary: 4900,
        age: 34,
        healthStatus: 'Здоровий',
        dateOfHiring: '2018-10-15',
        lastAppointment: '2023-03-20'
    },
    {
        id: 12,
        fullName: 'Корольова Ольга Володимирівна',
        passportData: 'II999999',
        education: 'Вища',
        specialty: 'HR-спеціаліст',
        department: 'HR',
        position: 'HR менеджер',
        salary: 4400,
        age: 68,
        healthStatus: 'Здорова',
        dateOfHiring: '2019-01-20',
        lastAppointment: '2023-05-15'
    },
    {
        id: 13,
        fullName: 'Єрьоменко Ігор Васильович',
        passportData: 'JJ101010',
        education: 'Вища',
        specialty: 'Архітектор',
        department: 'Архітектура',
        position: 'Головний архітектор',
        salary: 4700,
        age: 38,
        healthStatus: 'Здоровий',
        dateOfHiring: '2020-05-25',
        lastAppointment: '2023-04-10'
    }
]

export default personnel;